name: author_hub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  library_repository:
    path: packages/library_repository
  library_api:
    path: packages/library_api
  bloc: ^8.0.2
  http: ^0.13.4
  provider: ^6.0.2
  rxdart: ^0.27.3
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

